#!/usr/bin/env bash
# A Bash script that displays a detailed list of all running processes in a user-friendly, hierarchical format

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
